### ISSUE TITLE
Error running for first time

### ISSUE THREAD

**Issue by sergioIGZ** [Akryum/peeky#33]
I'm getting this error:
just doing the first steps`npm i -D @peeky/cli` => including the scripts in the package and then running the tests as `npm run test`
```
> peeky run

...some_path/node_modules/@peeky/cli/dist/bin.js:10863
    const port = options.port ?? process.env.PORT ?? await import_portfinder.default.getPortPromise({
                               ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Akryum** [comment]
What is your node version?

**Comment by sergioIGZ** [comment]
v12.22.1

**Comment by Akryum** [comment]
Could you try with Node 14 and Node 16 please?

**Comment by sergioIGZ** [comment]
It worked thank, unfortunately I cannot change the node version for my project because of some constraints.
Thank you anyways :)

**Comment by Akryum** [comment]
I don't think I'll have enough time to support Node 12. Closing for now.
