### ISSUE TITLE
Running multiple files: Cannot read properties of undefined (reading 'some')

### ISSUE THREAD

**Issue by distantnative** [Akryum/peeky#47]
When running multiple test files, I get the following error for every file but the first. The first succeeds:

```
 ERROR  Running tests failed: TypeError: Cannot read properties of undefined (reading 'some')(/@fs//kirby/panel/src/helpers/color.test.js)
    at matchModuleFilter (file://kirby/sandbox/kirby/panel/node_modules/@peeky/runner/src/runtime/vite.ts:319:18)
    at shouldExternalize (file://kirby/sandbox/kirby/panel/node_modules/@peeky/runner/src/runtime/vite.ts:311:7)
    at cachedRequest (file://kirby/sandbox/kirby/panel/node_modules/@peeky/runner/src/runtime/vite.ts:169:9)
    at executeWithVite (file://kirby/sandbox/kirby/panel/node_modules/@peeky/runner/src/runtime/vite.ts:121:25)
    at AsyncFunction.runTestFile (file://kirby/sandbox/kirby/panel/node_modules/@peeky/runner/src/runtime/run-test-file.ts:101:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I have tested each file on its own and then tests pass successfully.

(Peeky 0.8.2)

Please let me know what additional information would help (ps such great work you do!).

**Comment by Akryum** [comment]
https://github.com/Akryum/peeky/releases/tag/v0.8.3
